services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: spring-app

    ports:
      - "8080:8080"

    environment:
      SPRING_PROFILES_ACTIVE: pg

      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/cib7db
      SPRING_DATASOURCE_USERNAME: sg
      SPRING_DATASOURCE_PASSWORD: scooter

    restart: unless-stopped