server:
  port: 8080

spring:
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: gemma3:4b
  application:
    name: cib7ai
  web:
    locale: hu_HU
    local-resolver: fixed
    locale-date-format: yyyy-MM-dd HH:mm:ss

  datasource:
    url: jdbc:postgresql://localhost:5432/cib7db
    driver-class-name: org.postgresql.Driver
    username: sa
    password: 

  h2:
    console:
      enabled: true
      path: /sg-console

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC
          lob:
            non_contextual_creation: true
        id:
          new_generator_mappings: true

  mail:
    protocol: smtp
    host: mail.example.hu
    port: 587
    username: noreplay-info@example.hu
    password: ${MAIL_PASSWORD}
    properties:
      mail.transport.protocol: smtp
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

minio:
  url: http://localhost:9000
  access-key: admin
  secret-key: admin123

camunda:
  bpm:
    auto-deployment-enabled: false

    admin-user:
      id: sg
      password: 
      firstName: SG

    filter:
      create: All tasks

    database:
      schema-update: true

    authorization:
      enabled: false

    history-level: full

    job-execution:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: loggers,health,info,metrics,mappings

springdoc:
  api-docs:
    path: /api-docs

  swagger-ui:
    path: /swagger-ui.html

logging:
  file:
    name: cib7ai.log

  level:
    ROOT: INFO
    org.camunda: INFO
    hu.sg: DEBUG

devEnvironment: true